[package]
name = "milos-mazes"
version = "0.3.0"
authors = ["Erik Aker <eraker@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.0.0-beta.5", features = [ "derive" ] }
petgraph = "0.6.0"
raqote = "0.8.0"
rand = "0.8.3"